
FROM mcr.microsoft.com/vscode/devcontainers/python:3.9

# Install additional dependencies if needed
RUN pip install --upgrade pip

# Set the default shell to bash instead of sh
SHELL ["/bin/bash", "-c"]